apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: qlas
    type: api
  namespace: qlas
spec:
  replicas: 2
  selector:
    matchLabels:
      type: api
  template:
    metadata:
      labels:
        app: qlas
        type: api
    spec:
      containers:
        - name: container-api-server
          image: abitsugar/qlas-api:tagVersion
          env:
            - name: NQ_DB_HOST
              value: svc-database
            - name: NQ_DB_USER
              value: root
            - name: NQ_DB_PASSWORD
              value: password
            - name: NQ_DB_NAME
              value: dbqlas
          ports:
            - containerPort: 2017

---

apiVersion: v1
kind: Service
metadata:
  name: svc-app
  labels:
    name: svc-app
    type: api
  namespace: qlas
spec:
  type: NodePort
  selector:
    type: api
  ports:
    - port: 2017
      targetPort: 2017
      nodePort: 30303